### ISSUE TITLE
Set Keyframe Node is not working properly for shape keys.

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1042]
Hi...
Here is an example, I'm trying to set keyframes on shape key value with Set Keyframe Node. It is not working with shape keys, however, it is working for object location, rotation etc.
![shapekeys1](https://user-images.githubusercontent.com/30294746/54024532-09789580-41be-11e9-8bb5-5e1739807031.png)

For the time being. I'm using expression node to set keyframes:
![shapekeys2](https://user-images.githubusercontent.com/30294746/54024549-139a9400-41be-11e9-960a-7c9f3d0629e3.png)

**Comment by OmarSquircleArt** [comment]
Fixed in f563bd0.

**Comment by 3DSinghVFX** [comment]
@OmarSquircleArt  Set Keyframe Node still does not allow to set the keyframe. Or Do I miss something?
Thanks.

![ShapeKeys2](https://user-images.githubusercontent.com/30294746/54066987-8445bd00-425f-11e9-8fbf-cd284ee966c6.png)

**Comment by OmarSquircleArt** [comment]
You path is wrong, there is no such thing as `value`. Use the full path like `data.shape_keys.key_blocks["Key 1"].value`.

**Comment by 3DSinghVFX** [comment]
Thanks, @OmarSquircleArt
