### ISSUE TITLE
Vertex Offset Node changed the output data of Mesh Object Input Node in Blender 2.8x

### ISSUE THREAD

**Issue by 3DSinghVFX** [JacquesLucke/animation_nodes#1181]
Hi...
I have noticed that Vertex Offset Node changes the output data of Mesh Object Input Node in Blender 2.8x.
![DataProblem1](https://user-images.githubusercontent.com/30294746/64477932-ca53ed00-d1be-11e9-90d6-d85dc0d1c692.png)

Thanks :)
[DataProblem1.zip](https://github.com/JacquesLucke/animation_nodes/files/3586817/DataProblem1.zip)

**Comment by OmarSquircleArt** [comment]
Thanks for the report! Fixed in 68a3447.

**Comment by 3DSinghVFX** [comment]
Omar, the problem is still there with **Vertex Locations**, 
![DataProblem1](https://user-images.githubusercontent.com/30294746/64487157-5e23c880-d254-11e9-8d7c-a784f2cb8755.png)

**Comment by OmarSquircleArt** [comment]
The non-mesh outputs of the *Mesh Object Input* node are actually the attributes of the mesh output, since the mesh is not copied, the outputs return the modified attributes. For now, just use the Mesh Info node.
