### ISSUE TITLE
Blender crashes during rendering or exporting animations.

### ISSUE THREAD

**Issue by OmarEmaraDev** [JacquesLucke/animation_nodes#1200]
# What is the issue?

Blender crashes during rendering or exporting animations implemented using Animation Nodes. The crash is not always reproducible, but it seems highly reproducible in certain cases. In particular, when Animation Nodes is adding/removing objects or altering object data such as meshes or splines.

# Why haven't we fixed this issue yet?

The issue is caused by an upstream Blender bug, or rather, a design limitation. Consequently, there wasn't much we can do. However, we are currently looking into possible workarounds to mitigate the issue.

# What can I do to render my animation?

To render your animation, you may try to use one of the following methods. Non of the methods are guaranteed to work, but they proved effective in many situations.

## Background Render

You may try to render the animation in the background (Without the UI). To do so, execute blender from the terminal/console using the `-b` flag. For instance:

```bash
blender -b filename.blend -a
```

For more details and examples, see the Blender [man page](https://www.mankier.com/1/blender#Examples_(TL;DR)).

## Render Individual Frames

You may try to render frames individually using the following script:

```python

import bpy

scene = bpy.context.scene
render = scene.render
directory = render.filepath

for i in range(scene.frame_start, scene.frame_end):
    scene.frame_set(i)
    render.filepath = f"{directory}{i:05d}"
    bpy.ops.render.render(write_still = True)

render.filepath = directory 

```

The script render frames from *Start Frame* to *End Frame* and saves them in the scene's file path directory.

**Comment by juangea** [comment]
Shouldn't this be fixed already in latest 2.81?

I think I remember Sergey solved the culprip bug about this, but there could still be some crashes, but those crashes were solved enabling "lock interface" while rendering.

**Comment by OmarEmaraDev** [comment]
@juangea We are still not sure if what Sergey did actually solved the issue. In Animation Nodes, we use timers for automatic execution, while Sergey was talking about handlers. Some users also reported that the crashes still happen. I tried couple of tests scenes and Blender crashed even with "Lock Interface" enabled. However, it never crashed when using the two methods outlined above.
Can you try some scene and report back?

**Comment by samytichadou** [comment]
Hi, would it be a good idea to make a kind of "poor boy render operator" based on this kind of frame by frame script shipping with AN ? In case users can't render in a classic way their animation without crash, there would be a simple out of the box solution !

**Comment by OmarEmaraDev** [comment]
@samytichadou I guess we can consider that. But I am planning on diving deeper into the problem at some point because even the described methods don't work all the time.

**Comment by samytichadou** [comment]
> 
> 
> @samytichadou I guess we can consider that. But I am planning on diving deeper into the problem at some point because even the described methods don't work all the time.

neat :D great news ! 
meanwhile, if i have spare time, i'll made a quick poor boy operator patch to have quick solution while it is not solved, i had to use this kind of scripts a lot with AN, a proper op would be handy ! i'm feeling pythonic these days ;)

**Comment by erhn-gif** [comment]
a solution for those who still have a problem about animation nodes rendering:
1-animate with animation nodes, 
2-add start-end keyframes but not only for driver mesh; but also all driven meshes,
3-do render settings how do you want, and don't forget to enter output path
4-quit blender UI
5-win+x and open windows command prompt (admin)
6-enter this: 
cd C:\Program Files\Blender Foundation\Blender 2.81\
(enter blender path wherever it is in your comp.)
7-enter this:
blender -b file.blend -a
(write the location of your .blend file with animation nodes you want to render)

**Comment by Gerstmann-Bradley** [comment]
I found render from viewport can also work. The good part is that it allows me to render mp4 directly, since I don't know how to use a script to render a mp4 instead of an img sequence.

**Comment by ewhac** [comment]
Is there any value in providing .blend files that reliably crash?

**Comment by OmarEmaraDev** [comment]
We can reproduce the issue readily. However, it is rooted in Blender itself, so it is much harder to solve, as we can only implement a workaround, not a proper fix.

**Comment by OmarEmaraDev** [comment]
@ewhac On second thought, it would be nice if you can provide a blend file that can reliably crash. Thanks in advance!

**Comment by ewhac** [comment]
@OmarEmaraDev: Cool, where should I send it?

**Comment by OmarEmaraDev** [comment]
@ewhac I think you can just zip it and attach it here.

**Comment by Gerstmann-Bradley** [comment]
Hi, Omar, thanks for the new edition that makes AN much more stable, but there are still circumstances that the render seems not working properly.
(To distinguish the regular crash/other issues compared to AN crash,
the criteria is based on whether the script will work perfectly or not.)
Windows 10. blender version. 2.82.6. AN version upto 1/28/2020.

1. About crashes.
Firslty, the crash is very inconsistent, sometimes it works perfectly fine, sometime it will crash at random frames. Also the risk of crash seems different according to the actual the node tree.
The inconsistency itself seems very similar to what's in the past.
The difference compared to the past is that the success rate has been dramatically increased.
A simplified blender file is attached:

I rendered this file for several time. In ten times of rendering, it crashed five times.
(I can imagine, that the old AN will crash everytime.)
During the rendering, usually the render is very fast, but there are certain points the image editor will stall during rendering, and at that moment it has higher risk of crash.
There was one time the rendering of several frames have been stopped for a very long time for unknown reason, it recovered to render, but still stopped and finally just crashed at some point....

[text crash report.zip](https://github.com/JacquesLucke/animation_nodes/files/4155297/text.crash.report.zip)

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley I can't replicate the crash, unfortunately.

Can anybody else reproduce that crash? @3DSinghVFX Can you try that?

**Comment by 3DSinghVFX** [comment]
> Can anybody else reproduce that crash? @3DSinghVFX Can you try that?

@OmarEmaraDev I have rendered animation for different blend files (also the provided one) but I can't replicate the crash.

**Comment by Gerstmann-Bradley** [comment]
No problem, I can only the crash doesn't occur as frequently as in the past.
I will go to this problem later. Thanks for checking.

**Comment by OmarEmaraDev** [comment]
@Gerstmann-Bradley Can you try locking the UI while rendering?

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev Sorry. After trying multiple times it blender does crash,
![Screenshot from 2020-02-05 17-52-45](https://user-images.githubusercontent.com/30294746/73841388-88e46e00-4840-11ea-83c2-faa7cb7137f4.png)

**Comment by 3DSinghVFX** [comment]
Here is the crash report,

# Blender 2.83 (sub 2), Commit date: 2020-02-04 11:40, Hash cd0a02862404

# backtrace
./blender(BLI_system_backtrace+0x1d) [0x6fc638d]
./blender() [0x1659702]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fa5933314b0]
./blender() [0x19c41b1]
./blender() [0x19c7520]
./blender(BLI_task_pool_work_and_wait+0x159) [0x6fc7709]
./blender(mesh_buffer_cache_create_requested+0xeb5) [0x19cab05]
./blender(DRW_mesh_batch_cache_create_requested+0x9bd) [0x19a431d]
./blender() [0x19548f0]
./blender(DRW_draw_render_loop_ex+0x547) [0x19564d7]
./blender(view3d_main_region_draw+0x77) [0x1f2e8e7]
./blender(ED_region_do_draw+0x8f1) [0x1b6c311]
./blender(wm_draw_update+0x4ae) [0x181ecbe]
./blender(WM_main+0x30) [0x181cd10]
./blender(main+0x317) [0x159fde7]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fa59331c830]
./blender() [0x1655fac]

**Comment by 3DSinghVFX** [comment]
Here is the crash report for Blender2.82

# Blender 2.82 (sub 6), Commit date: 2020-02-04 10:05, Hash 2264590d8cc9

# backtrace
./blender(BLI_system_backtrace+0x1d) [0x6fba06d]
./blender() [0x1658659]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7f7c786d34b0]
./blender() [0x19c2ac1]
./blender() [0x19c6080]
./blender(BLI_task_pool_work_and_wait+0x159) [0x6fbb3e9]
./blender(mesh_buffer_cache_create_requested+0xeb5) [0x19c92c5]
./blender(DRW_mesh_batch_cache_create_requested+0x9bd) [0x19a2dad]
./blender() [0x1952f40]
./blender(DRW_draw_render_loop_ex+0x547) [0x1954b27]
./blender(view3d_main_region_draw+0x77) [0x1f2c367]
./blender(ED_region_do_draw+0x8f1) [0x1b6a251]
./blender(wm_draw_update+0x496) [0x181d446]
./blender(WM_main+0x30) [0x181b4b0]
./blender(main+0x317) [0x159ed47]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f7c786be830]
./blender() [0x1654f0c]

**Comment by Gerstmann-Bradley** [comment]
> @Gerstmann-Bradley Can you try locking the UI while rendering?

Yes, it seems locking interface largely helps the issue in this particular file..
In seven times of rendering, no crash at all.
Will see if crash occur in actual more complex file in the future. Thanks for the suggestions.

**Comment by OmarEmaraDev** [comment]
Ok. I still can't reproduce the issue. But this is a known limitation in Blender. Just lock the UI before rendering for now.

**Comment by 3DSinghVFX** [comment]
@OmarEmaraDev I have rendered the animation of the provided file with _Lock UI_ for 25 times without the Blender crash.

**Comment by OmarEmaraDev** [comment]
Fixed in #1294 and b1ac938.

**Comment by Ammusionist** [comment]
For what it's worth, I have a simple work around for this.
I was using TimeInfo - Frame to update a Text Strip in VSE and couldn't get it to update during Render.

Fix: Added a Custom trigger pointed to the current scene and "frame_current" property.
![image](https://user-images.githubusercontent.com/6345296/76301549-5a115a00-630e-11ea-9565-c657751dbaf1.png)

Updated on each frame change like a charm.

**Comment by gurlaldeepsingh** [comment]
tried everything but it's still crashing

**Comment by Finnste** [comment]
> For what it's worth, I have a simple work around for this.
> I was using TimeInfo - Frame to update a Text Strip in VSE and couldn't get it to update during Render.
> 
> Fix: Added a Custom trigger pointed to the current scene and "frame_current" property.
> ![image](https://user-images.githubusercontent.com/6345296/76301549-5a115a00-630e-11ea-9565-c657751dbaf1.png)
> 
> Updated on each frame change like a charm.

Can you or anyone elaborate this solution a bit further?
Still can't find a way that AN updates while rendering..

**Comment by OmarEmaraDev** [comment]
@Finnste What exactly is the issue? Are you using the latest Animation Nodes version?

**Comment by Finnste** [comment]
Yes. I am looping through two object instancers, creating two objects for each vertex in a mesh. On text object and one empty controller, reading the vertices z-position and handing it over to the text value. Works like a charme in the viewport, but Blender crashes when I attempt to render. So I render from the command line, but then I have the problem that AN doesn't seem to update, the text values remain the same from the last time I saved the scene. No change wether I render individual frames, range or the whole animation. Thanks for any help.

![Annotation 2020-06-24 125439 (1)](https://user-images.githubusercontent.com/55399974/85543247-2be42b80-b61a-11ea-86b5-90b548a3ed20.png)

**Comment by OmarEmaraDev** [comment]
@Finnste I believe locking the UI should protect you against crashes. As for not updating, I would have to take a closer look at your setup. What does `getControllerLoc` do exactly?

**Comment by Finnste** [comment]
I'm sorry for such a trivial question but how to lock the UI? I've failed to find any information on this as I previously read about this fix in this thread. 

getControllerLocation 
`import bpy
x,y,z = controler.matrix_world.translation
return z`
If needed I can send you the .blend

Thanks for the help!

**Comment by OmarEmaraDev** [comment]
@Finnste In the top bar, *Render* -> *Lock Interface*.

The `getControllerLocation` is probably the issue here. You should replace this with the *Matrix Input* and *Decompose Matrix* nodes. Alternatively, if you really want to use a script node, you have to evaluate the object ID first as follows:

```
evaluatedController = AN.utils.depsgraph.getEvaluatedID(controler)
x, y, z = controler.matrix_world.translation
```

Moreover, you don't need to import bpy as it is already imported for you. Finally, script nodes shouldn't return anything. Your output should be named z and it should work by writing to a variable z. See the following documentation:

https://docs.animation-nodes.com/documentation/subprograms/script/

**Comment by Finnste** [comment]
Thank you very very much for your quick help, also for a beginner like me. Using Matrix Input seems to solve my problem and also lock interface prevents Blender to crash.

**Comment by alessandro-zomparelli** [comment]
Just a turnaround, but maybe it may help someone. I created an operator in Tissue in order to render all the frames allowing to press ESC for Cancel the operation. I have the same problem with Animated Tessellations with Tissue add-on. I cannot render the animation or export as alembic:
![image](https://user-images.githubusercontent.com/6708848/87643590-51f97900-c74b-11ea-98a4-1ad63cc01dd1.png)
![image](https://user-images.githubusercontent.com/6708848/87643622-59208700-c74b-11ea-81de-068ac72bf90c.png)

It's currently available in the development branch of Tissue: https://github.com/alessandro-zomparelli/tissue/tree/b280-dev
Looking forward to find a real solution to this issue though...

**Comment by OmarEmaraDev** [comment]
@alessandro-zomparelli Did you take a look at #1294 and b1ac938?

**Comment by alessandro-zomparelli** [comment]
> @alessandro-zomparelli Did you take a look at #1294 and [b1ac938](https://github.com/JacquesLucke/animation_nodes/commit/b1ac938f9c68d349cbdef0bf89d864f8df15a58c)?

Thanks, I'll check it!

**Comment by alessandro-zomparelli** [comment]
> @alessandro-zomparelli Did you take a look at #1294 and [b1ac938](https://github.com/JacquesLucke/animation_nodes/commit/b1ac938f9c68d349cbdef0bf89d864f8df15a58c)?

Hi Omar, thanks for the hint. I gave a look to your strategy and I tried to adapt to my code, but then I realized that during the Tessellation I'm actually adding and deleting some modifiers each time. I'm worried that this doesn't allow me to use the `DAG_EVAL_RENDER` . Is that correct? I understood that this is a picture of the dependencies graph passed by the event `frame_changed_post `, am I right?

**Comment by OmarEmaraDev** [comment]
@alessandro-zomparelli I see. I am not entirely sure if that will be a problem or if we can work around it. Can you point me in the direction of the code you are talking about? Maybe a minimal example that illustrates the issue would be nice as well.

**Comment by alessandro-zomparelli** [comment]
@OmarEmaraDev I'll try to explain: 

case 1) basically I use an array modifier inside the tessellation. 
I create a single copy of the original component, then I apply an array modifier to that, in order to have my desired mesh topology/indexes. Coordinates of the vertices of each component are elaborated with numpy, and then I use foreach_set() in order to adapt the  regular array to the target geometry. In my tests this was the most efficient way, maybe there is a better way though...

case 2) Another example is the Patch Tessellation, I need to compare a base mesh before and after the subdivision surface modifier, in order to have a structured grid for each subdivided face.

case 3) If more iterations are used, then I may have to repeat case 1 and 2 to the previously generated object.

**Comment by OmarEmaraDev** [comment]
It seems to me like it should work even with those ops.

**Comment by AticAtac80** [comment]
Hi everybody, I'm having the same issue: an not updating during animation render (i'm using time info for an overlaying frame counter + timing . I'm trying baking to frame with no result. Is it correct to render animation after baking?
Thanx

**Comment by OmarEmaraDev** [comment]
@AticAtac80 Are you using the latest version of Animation Nodes? https://animation-nodes.com/#download

**Comment by AticAtac80** [comment]
**@OmarEmaraDev** 
I've tried many versions on Blender 2832. I've experienced both no frame update values on render frame and, when working, random crash in a range of 2-120 frames from start.
I would go for the baking workaround, but if once baked the procedure is render animation this not worked for me (still effect not updated in render frames)
Thanx for the link! I wil check and report result asap.

**Comment by AticAtac80** [comment]
**@OmarEmaraDev**
Still no update of rendered frames: the frame+time counter based on time info (see attached ss) freezes the frame datas of the current curson position on the viewport for EVERY rendered frame of the animation.
Blender 2832
AN from suggested link
VC_redist.x64 installed
![Untitled-1](https://user-images.githubusercontent.com/68369104/88370297-133e7100-cd92-11ea-8b36-a4a00a5fea21.jpg)

**Comment by AticAtac80** [comment]
Auto exection ON

**Comment by OmarEmaraDev** [comment]
@AticAtac80 Can you add the file?

**Comment by AticAtac80** [comment]
> 
> 
> @AticAtac80 Can you add the file?

It's a video edit. Is it ok for you without the linked video sequences?

**Comment by OmarEmaraDev** [comment]
@AticAtac80 Yes.

**Comment by AticAtac80** [comment]
Thanx for your help! :-)
[Edit with Anim Nodes.zip](https://github.com/JacquesLucke/animation_nodes/files/4973390/Edit.with.Anim.Nodes.zip)

**Comment by OmarEmaraDev** [comment]
@AticAtac80 I can replicate the issue. I will investigate.

**Comment by OmarEmaraDev** [comment]
@AticAtac80 Seems like a Blender bug where the frame change handlers don't execute if the sequencer exists in the rendering pipeline. I will confirm it and report it to the developers.

**Comment by AticAtac80** [comment]
> 
> 
> @AticAtac80 Seems like a Blender bug where the frame change handlers don't execute if the sequencer exists in the rendering pipeline. I will confirm it and report it to the developers.

Great! Will wait for the news! :-)

**Comment by Misterdudeman** [comment]
Any update on this thread?

**Comment by OmarEmaraDev** [comment]
@Misterdudeman What issue are you having?

**Comment by Misterdudeman** [comment]
Same issues as this thread. In addition I'm having differences in renders from single frame to command line renders.
Currently the Render By Frame script seems to be working for me but its not ideal.
I tried the trigger frame_current which seems to help the Render By Frame but not Render Animation.
From profiling my graph I have a feeling that there is an accumulation of node updates that get more and more out of sync with the global time as cycles doesn't always seem to rebuild the graph for every frame when running an animation range on its own.
I have also turned off sequencer in the render pipe but haven't noticed a difference.
I'm running AN 2.1.7 + Extra Nodes and Blender 2.83.

**Comment by OmarEmaraDev** [comment]
@Misterdudeman Does enabling Lock User Interface fixes the crashes? What kind of differences are you experiencing?

**Comment by Misterdudeman** [comment]
It seemed to help it not crash but still didn't run correctly in the Render Animation.

**Comment by OmarEmaraDev** [comment]
Lock User Interface should always be enabled when rendering AN animations, there is no way around it unfortunately.
What is the expected output of your animation and what did you get instead? It would be nice if you attach the node tree as well.

**Comment by imacj** [comment]
Not sure if anyone has suggested this, but baking the keyframes for each node tree and then disabling the node trees did the trick for me!

**Comment by EstEsca** [comment]
> Not sure if anyone has suggested this, but baking the keyframes for each node tree and then disabling the node trees did the trick for me!

Wow, this one really saved me! Thanks a lot
