### ISSUE TITLE
Got bug of this release 2.0 beta on Mac (jasperge)

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#706]
Traceback (most recent call last):
  File "/Users/jimmygunawan/Documents/blender-2.78b-OSX_10.6-x86_64/blender.app/Contents/MacOS/../Resources/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/animation_nodes/__init__.py", line 114, in <module>
    modules = import_modules.importAllSubmodules(__path__[0], __package__)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.78/scripts/addons/animation_nodes/import_modules.py", line 8, in importAllSubmodules
    module = importlib.import_module("." + name, packageName)
  File "/Users/jimmygunawan/Documents/blender-2.78b-OSX_10.6-x86_64/blender.app/Contents/Resources/2.78/python/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "animation_nodes/data_structures/splines/poly_spline.pxd", line 5, in init animation_nodes.algorithms.mesh_generation.cylinder (/Users/jasperge/dev/blender_addons/animation_nodes_cython/animation_nodes/algorithms/mesh_generation/cylinder.c:4626)
    cdef class PolySpline(Spline):
ValueError: animation_nodes.data_structures.splines.poly_spline.PolySpline has the wrong size, try recompiling. Expected 56, got 64

**Comment by enzyme69** [comment]
Hmm... so many issues because I am not using Blender 2.8 maybe? 

I won't use non official I guess.

**Comment by jasperges** [comment]
Although you already closed this issue, I still would like to find out what's wrong. Just to be sure: did you completely remove any older version(s) you had installed?
I tested in on Blender 2.78c and (just now) on Blender 2.78b. It works fine for me.

The weird thing is: when I tried this version of AN I got basically the same error message as you, but for me it said `Expected 64, got 56` (so exactly the other way around). Then i did a clean clone from git and compiled again and then it worked.
I don't know much about Cython, so I don't if this is a problem in the code or with the compilation. @JacquesLucke Do you have any ideas?

**Comment by JacquesLucke** [comment]
This issue should always be solved by a clean compile. So maybe you should upload your newly compiled version.

Cython compiles every pyx file into a extension module. Furthermore I can create pxd files, that are like header files in c. When a pxd file is changed (in a certain way, eg I change a struct), all pyx files that depend on this file have to be recompiled. Cython sometimes does not automatically detect this. So some files use the old declaration of a struct and some the newer declaration. When importing the extension modules into Python in Blender it checks whether all the struct declarations match or not. If not, it raises the error we see here.

**Comment by jasperges** [comment]
The version I uploaded was the cleanly compiled version.
I think I understand what you are saying, but I still don't get why this happened, because I did a clean compilation. Anyway, I re-compiled with the latest commits (hash `ab3968f7`) and re-uploaded to graphicall.
@enzyme69 Could you try again and make sure you first completely remove the old version?

**Comment by JacquesLucke** [comment]
what exactly do you mean when you say you did a clean compile?

Maybe there were some leftovers in the working directory that were not removed. I just got an idea what might cause this problem.
When you do `python setup.py --all` it removes all c files cython generated. However, the compiled files are not removed. Usually they overwritten by the new compiled files, but not when the corresponding pyx file has been removed in the meantime.
This can be considered a bug in the setup.py file, will fix this later today.

**Comment by jasperges** [comment]
I cloned a 'fresh' version from github and compiled it. So there weren't any leftovers from previous compiles.

So I understand why I got the `Expected 56, got 64` error when I didn't compile a fresh git clone, but what I don't understand is why @enzyme69 got `Expected 64, got 56` error with the compiled version (which worked for me) from a fresh git clone. When my newly uploaded version works, I will blame it on myself for messing something up somewhere... 😊
