### ISSUE TITLE
Have issue installing AN 2.1 on Mac Blender 2.8

### ISSUE THREAD

**Issue by enzyme69** [JacquesLucke/animation_nodes#961]
Is this because I have previous AN add-on?

```
reloading addon: animation_nodes 1544910486.8574095 1544910962.3037305 '/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/__init__.py'
Modules Installed () from '/Users/jimmygunawan/Downloads/animation_nodes_v2.1_blender2.80_macOS_py37.zip' into '/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons'
GPUShader: compile error:
ERROR: 0:72: Use of undeclared identifier 'gl_FragColor'

Traceback (most recent call last):
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181215.351f537fa83-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/__init__.py", line 166, in <module>
    auto_load.init()
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 23, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 51, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/auto_load.py", line 55, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/Users/jimmygunawan/Downloads/blender-2.80.0-git20181215.351f537fa83-x86_64/blender.app/Contents/Resources/2.80/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/viewer/viewer_3d.py", line 19, in <module>
    matricesShader = getShader(os.path.join(os.path.dirname(__file__), "matrix_shader.glsl"))
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/graphics/import_shader.py", line 10, in getShader
    return gpu.types.GPUShader("\n".join(lines[:i]), "\n".join(["\n"] * index + lines[i:]))
Exception: Shader Compile Error, see console for more details

```

**Comment by enzyme69** [comment]
Or is it because of this? MacBookPro 2017
<img width="269" alt="screen shot 2018-12-16 at 9 00 36 am" src="https://user-images.githubusercontent.com/3952687/50047801-15017680-0111-11e9-853a-575829e97c7f.png">

**Comment by JacquesLucke** [comment]
Thanks. 
Maybe this fixes it: https://stackoverflow.com/a/26695347/4755171

It should be possible for you to try that fix by changing two lines of code or so. However I don't know which ones right now (I'm on my phone).
Will give more detailed instructions tomorrow.

**Comment by OmarSquircleArt** [comment]
Navigate to `animation_nodes/nodes/viewer/matrix_shade.glsl`. After the line `// Fragment Shader`, change the code to:

```
flat in vec4 v_Color;
out vec4 fragColor;

void main()
{
    fragColor = v_Color;
}
```
Does this solve the problem?

**Comment by enzyme69** [comment]
@OmarSquircleArt Yes, it seems to work!!! And holy crap AN in Blender 2.8 is FAST!

**Comment by frf2436** [comment]
hello
problem with animation node on mac 2017 mojave
<img width="2048" alt="capture d ecran 2018-12-25 a 18 51 17" src="https://user-images.githubusercontent.com/46136315/50425435-37fcfa80-0876-11e9-88aa-29e8cac96fc2.png">
<img width="979" alt="capture d ecran 2018-12-25 a 18 52 46" src="https://user-images.githubusercontent.com/46136315/50425441-4d722480-0876-11e9-82c3-96c9d05c8349.png">

**Comment by OmarSquircleArt** [comment]
@frf2436 Thanks for the report. This was already fixed.

**Comment by nch3d** [comment]
Not update in EEVEE active or Cycles view rendered. Only run on other (wire, solid, lookDev) (MacPRO Xeon, MacPRO OS High Sierra AMD D700, 2 Intel-Xeon.

**Comment by nch3d** [comment]
![screen shot 2019-01-06 at 4 52 58 am](https://user-images.githubusercontent.com/46262085/50735148-709ead00-116f-11e9-91bc-568345c92443.png)
![screen shot 2019-01-06 at 4 53 41 am](https://user-images.githubusercontent.com/46262085/50735149-75636100-116f-11e9-863d-4636f9c8c16d.png)

High Sierra 10.13 MacPRO Intel Xeon D700

**Comment by OmarSquircleArt** [comment]
@nch3d Thanks for the report, this was already fixed. Please open a new issue for further reports.

**Comment by nch3d** [comment]
> @nch3d Thanks for the report, this was already fixed. Please open a new issue for further reports.
@OmarSquircleArt 
it's not fixed, where do I download the fix? Link please, I will appreciate it very much.
![screen shot 2019-01-06 at 6 14 07 am](https://user-images.githubusercontent.com/46262085/50735837-89f92680-117a-11e9-9332-45dab63ef896.png)

Here https://github.com/JacquesLucke/animation_nodes/releases no work.

**Comment by nch3d** [comment]
> @nch3d Thanks for the report, this was already fixed. Please open a new issue for further reports.

@OmarSquircleArt  Thanks.... find https://github.com/JacquesLucke/animation_nodes/commit/f69dda0e1b6ad2da1ed9fd37dda839bf8815370c#diff-0af26f9b9db107e7409421702476aa04
