### ISSUE TITLE
Particle data node not working AN 2.1 Blender 2.80

### ISSUE THREAD

**Issue by tofuhead** [JacquesLucke/animation_nodes#973]
Trying to get locations of particles, but the node gives out empty list..

.b

**Comment by OmarSquircleArt** [comment]
Yes, we are aware about this issue. Unfortunately, this is related to Blender itself, so we will implement a fix as soon as this gets fixed in Blender.

**Comment by OmarSquircleArt** [comment]
Fixed in 205bab2.

**Comment by lukad** [comment]
Should this be reopened? I see that the fix was reverted in 6158c32ffcb19b70303dfb8cd271acc9d3290e5b and it's still broken in the blender2.8 branch.
I also tried using the fix by checking it out directly and it wasn't working for me.

**Comment by OmarSquircleArt** [comment]
@lukad  Oh yes, sorry.

---
If one want to get particle info for now, you can use the following expression to evaluate the depsgraph:

```python
bpy.context.depsgraph.objects.get(object.name)
```

This object can then be used to get the particle system and get its data as follows:

![Node Tree](https://user-images.githubusercontent.com/25300994/53248822-4e310680-36bf-11e9-97e1-fc463d6dc826.png)

**Comment by lukad** [comment]
Thanks for providing the workaround! 👍

**Comment by OmarSquircleArt** [comment]
Fixed in 9dbeeda.

**Comment by Tokenyet** [comment]
![image](https://user-images.githubusercontent.com/6420527/54682756-bb16af80-4b4a-11e9-9827-aafe08216fb5.png)

@OmarSquircleArt
Thanks for the solution and this project!  I just got an another question, If there is a way to add a GroupInput  between Expression and Object Input? I want to control the source object. 😄
