### ISSUE TITLE
Separate Text Object bug on Mac

### ISSUE THREAD

**Issue by Jmartgraphix** [JacquesLucke/animation_nodes#999]
**Clicking the update button causes error -**

Traceback (most recent call last):
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/dynamic_operators.py", line 52, in invoke_InvokeFunction
    return self.execute(context)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/dynamic_operators.py", line 58, in execute_InvokeFunction
    self.an_executeCallback(self.callback, *args)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/extend_bpy_types.py", line 28, in _executeCallback
    executeCallback(callback, *args, **kwargs)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/callbacks.py", line 25, in executeCallback
    callback(*parameters, args, kwargs)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/operators/callbacks.py", line 40, in executeNodeCallback
    getattr(node, functionName)(*args, **kwargs)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/text/separate_text_object.py", line 90, in updateSeparation
    objects = splitTextObject(source)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/utils/blender_ui.py", line 84, in wrapper
    output = function(*args, **kwargs)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/text/separate_text_object.py", line 154, in splitTextObject
    sourceSplinePositions = getSplinePositions(sourceObject)
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/text/separate_text_object.py", line 194, in getSplinePositions
    curve = newCurveFromActiveObject()
  File "/Users/usmartja/Library/Application Support/Blender/2.80/scripts/addons/animation_nodes/nodes/text/separate_text_object.py", line 215, in newCurveFromActiveObject
    bpy.ops.object.convert(target = "CURVE", keep_original = True)
  File "/private/var/folders/gr/s92v1j110_j29q_8_hb1q4wnz354bc/T/AppTranslocation/A62825C2-4BE3-4A48-8EF5-C943C7C3B0D1/d/blender.app/Contents/Resources/2.80/scripts/modules/bpy/ops.py", line 200, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect

location: <unknown location>:-1

**Comment by OmarSquircleArt** [comment]
Thanks for the report, this was already fixed.

**Comment by DVSoftware** [comment]
This is still happening for me, in the latest version. 
Blender 2.90.1 on a Mac

**Comment by OmarEmaraDev** [comment]
@DVSoftware Seems to work fine here. Are you doing anything special? What are the steps to reproduce the issue?

**Comment by DVSoftware** [comment]
Strange, it works on another computer, it has the same OS version, but Blender is 2.91.0. I'll try to upgrade later and let you know.

**Comment by DVSoftware** [comment]
It seems it was a problem with Blender 2.90.1. It works fine in 2.91.0
